version: "2.4"
services:
  semrelay_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    network_mode: "host"
    cap_add:
      - NET_BIND_SERVICE
    restart: "no"
    environment:
      - DOMAIN=example.com
      - HTTP_ONLY=1
      - PASSWORD=password
      - TOKEN=token
      - VERBOSE=1
      - PORT=9021
