version: "2.4"
services:
  semrelay:
    image: cswheeler/semrelay:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    network_mode: "host"
    cap_add:
      - NET_BIND_SERVICE
    restart: "always"
    environment:
      - DOMAIN
      - EMAIL
      - PASSWORD
      - TOKEN
      - TEST
