FROM golang:1.17.3-bullseye AS builder
RUN mkdir /app
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . /app/
RUN env CGO_ENABLED=0 go build ./cmd/semrelay

FROM alpine:3.14.3
RUN apk add libcap
RUN mkdir /app
RUN chown nobody:nogroup /app
RUN chmod 755 /app
ENV HOME=/app
COPY --chown=nobody:nogroup --from=builder /app/semrelay /app/semrelay
RUN setcap cap_net_bind_service=+ep /app/semrelay
USER nobody:nogroup
CMD ["/app/semrelay"]
