name: CI
on: [push]
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - run: go install gotest.tools/gotestsum@v1.7.0
      - name: Unit tests
        run: gotestsum --junitfile unit.xml -f testname ./...
      - name: Integration tests
        run: ./run_integration
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./*.xml
